### PR TITLE
Queue fix

### PR DESCRIPTION
**Pull request by damoclark**
Hi Eric,

I have made some changes and improvements to the code base.  Submitting back to you as a PR if you wish to incorporate into your version.  The final commit summarises the changes made.

The primary change is the way in which polling is done, and how the queue is managed.  Chiefly, new commands are only added to the queue when a response to a previous command is received.  This limits chance of overflowing the queue.  I also hope it limits any potential race conditions.

My ELM327 when the ECU was powered off (ignition not switched on) would continually response with UNABLE TO CONNECT, but the library kept queueing commands to send.  The change was to address this.

Let me know if you do not wish to adopt these changes to your library, and I'll maintain a separate fork.

Thanks for writing your module.  It's be very helpful for my personal project.

### CODE REVIEW

**Comment by EricSmekens** [comment]
Firstly, thanks for your PR.
I would like to integrate your changes into this project.

But before I can do that and release to NPM, which should be done after quite a few fixes here and there by multiple user-efforts, I need to be able to test and refactor parts of the module.

Since you have some look into the code, I would like your opinion about it.
Currently I don't have a working simulation where I can test this stuff, or test improvements.

**Comment by damoclark** [comment]
No problem Eric,

I actually started by re-engineering the library using a finite state machine approach.  But it became too time consuming, and I wanted to get on with my project, so I just made the minimal changes to deal with the vagarities of the ELM327 clone I was using.  

I may still have a commit where I made a start using an npm module for FSM if you are interested in taking a look as a potential way forward in refactoring your library.  I can push the commit into my repo if you want to check it out.  Machina was the name of the FSM library.  It's extra work at the start, but I think the payoff is in simpler management of the interface and changes in state as its used.

My broader suggestion would be as you have suggested, to combine the two libraries (serial & bt), and create abstractions around the serial interface that they use.  For instance, both the bluetooth and RS232 (serial) devices share the same communications protocol with the ELM327, and the library interfaces to both serial devices (RS232 & BT) both use emitter prototypes.  This should reduce the duplication of effort on your part.  Your instructions to the developer using your library would simply be to install either the bluetooth or serial dependencies yourself according to your needs.  Your constructor could take an instantiated/connected serial object, or could detect the 'type' of serial object passed in and then connect according to its type.

In terms of testing and debugging, what I could do is attempt to write the raw data from my ELM327 to a flat file that you can then 'replay' as a pseudo serial device.  I'm sure you could write a simple object prototype that has a similar API to the bt or serial libraries, but reads its data from my file instead.  Won't be perfect, but its a start.  

When time permits, I could test releases for you.  

The other option is to simply buy a couple of these devices.  They are pretty inexpensive.

Let me know if you wish to take me up on anything herein.

Again, thanks for sharing your code.

Damien.

**Comment by EricSmekens** [comment]
I am going to set up a simulation environment with OBDSim, will try to test this.

**Comment by damoclark** [comment]
Nice find.  Should help a great deal with testing.  Might look into it myself.  I have a bluetooth module I want to get working too.

**Comment by EricSmekens** [comment]
I am probably going to revert this, as I overlooked the Licensing and I can't agree on it.

**Comment by damoclark** [comment]
Hey @EricSmekens ,

I'm afraid this is a miscommunication caused by me.  The licencing in the commit looks to be based on my former attempt to re-engineer the module using a FSM, and so the intent was clarifying that the original code was yours.  In particular, the code for obdInfo where you put in substantial effort in decoding the obd response codes.

The I changed my mind and decided just to submit a PR for the bit that I needed to fix for my ELM327.

So the change in licence wasn't meant to be included in the PR.  My PR change was hardly that ground breaking. :)

I can see how it looks, so my apologies for that.  I'm not at all wedded to the GPL licence - it's just what I normally use when I code which is how it ended up there.  

If you are still interested in including the PR, the licence comments can be removed, and the PR will fall under the bounds of your existing chosen licence as would normally happen with a PR.

I don't have access to my local git repo as I'm currently travelling.  You are welcome to remove the licence comments from the PR, or if you prefer when I return, I can remove them in a new commit for the PR.  

Let me know if you would like to proceed.

Regards,
Damien.

**Comment by EricSmekens** [comment]
Yeah, when I have time I will try to get everthing in without the license. (If you have time before this, another PR would be fine too.)

**Pull request merged**
